Update docker-compose-development.yml

diff --git a/docker-compose-development.yml b/docker-compose-development.yml
--- a/docker-compose-development.yml
+++ b/docker-compose-development.yml
@@ -1,18 +1,30 @@
-version: "3.8"
-
+```yaml
 volumes:
-  cargo_cache:
   pg_data:
-  router_build_cache:
-  scheduler_build_cache:
-  drainer_build_cache:
   redisinsight_store:
+  ckh_data:
 
 networks:
   router_net:
 
 services:
   ### Dependencies
+  prestart-hook:
+    image: curlimages/curl-base:latest
+    container_name: prestart-hook
+    environment:
+      - ONE_CLICK_SETUP=${ONE_CLICK_SETUP:-false}
+    entrypoint:
+      [
+        "/bin/sh",
+        "-c",
+        "apk add --no-cache bash && /bin/bash /prestart_hook.sh",
+      ]
+    volumes:
+      - ./scripts/prestart_hook.sh:/prestart_hook.sh
+    networks:
+      - router_net
+
   pg:
     image: postgres:latest
     ports:
@@ -20,7 +32,7 @@ services:
     networks:
       - router_net
     volumes:
-      - pg_data:/VAR/LIB/POSTGRESQL/DATA
+      - pg_data:/var/lib/postgresql/data
     environment:
       - POSTGRES_USER=db_user
       - POSTGRES_PASSWORD=db_pass
@@ -47,7 +59,11 @@ services:
 
   migration_runner:
     image: rust:latest
-    command: "bash -c 'cargo install diesel_cli --no-default-features --features postgres && cargo install just && just migrate'"
+    command: >
+      bash -c "
+      curl -fsSL https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash &&
+      cargo binstall diesel_cli just --no-confirm &&
+      just migrate"
     working_dir: /app
     networks:
       - router_net
@@ -56,57 +72,67 @@ services:
     environment:
       # format -> postgresql://DB_USER:DB_PASSWORD@HOST:PORT/DATABASE_NAME
       - DATABASE_URL=postgresql://db_user:db_pass@pg:5432/hyperswitch_db
+  
+  mailhog:
+    image: mailhog/mailhog
+    networks:
+      - router_net
+    profiles:
+      - full_setup
+    ports:
+      - "1025:1025"
+      - "8025:8025"
 
   ### Application services
   hyperswitch-server:
-    build:
-      dockerfile_inline: |
-        FROM rust:latest
-        RUN apt-get update && \
-            apt-get install -y protobuf-compiler
-        RUN rustup component add rustfmt clippy  
-    command: cargo run --bin router -- -f ./config/docker_compose.toml
-    working_dir: /app
+    image: docker.juspay.io/juspaydotin/hyperswitch-router:standalone
+    pull_policy: always
+    command: /local/bin/router -f /local/config/docker_compose.toml
     ports:
       - "8080:8080"
     networks:
       - router_net
     volumes:
-      - ./:/app
-      - cargo_cache:/cargo_cache
-      - router_build_cache:/cargo_build_cache
+      - ./config:/local/config
+      - ./files:/local/bin/files
     environment:
-      - CARGO_HOME=/cargo_cache
-      - CARGO_TARGET_DIR=/cargo_build_cache
+      - API_KEY=your_api_key # Replace with your Hyperswitch API key
+      - PUBLISHABLE_KEY=your_publishable_key # Replace with your Hyperswitch publishable key
+      - RESPONSE_HASH_KEY=your_response_hash_key # Replace with your Hyperswitch response hash key
+      - BASE_URL=https://hyperswitch.trendss.net/api
+      - WEBHOOK_URL=https://hyperswitch.trendss.net/api/webhook
     depends_on:
       pg:
         condition: service_healthy
       redis-standalone:
         condition: service_healthy
+      migration_runner:
+        condition: service_completed_successfully
     labels:
-      logs: "promtail"
+      - "traefik.enable=true"
+      - "traefik.http.routers.hyperswitch-server.rule=Host(`hyperswitch.trendss.net`) && PathPrefix(`/api`)"
+      - "traefik.http.routers.hyperswitch-server.entrypoints=websecure"
+      - "traefik.http.routers.hyperswitch-server.tls=true"
+      - "traefik.http.services.hyperswitch-server.loadbalancer.server.port=8080"
+      - logs: "promtail"
     healthcheck:
       test: curl --fail http://localhost:8080/health || exit 1
-      interval: 120s
-      retries: 4
-      start_period: 20s
-      timeout: 10s
+      interval: 5s
+      retries: 3
+      start_period: 5s
+      timeout: 5s
 
   hyperswitch-producer:
-    image: rust:latest
-    command: cargo run --bin scheduler -- -f ./config/docker_compose.toml
-    working_dir: /app
+    image: docker.juspay.io/juspaydotin/hyperswitch-producer:standalone
+    pull_policy: always
+    command: /local/bin/scheduler -f /local/config/docker_compose.toml
     networks:
       - router_net
     profiles:
       - scheduler
     volumes:
-      - ./:/app
-      - cargo_cache:/cargo_cache
-      - scheduler_build_cache:/cargo_build_cache
+      - ./config:/local/config
     environment:
-      - CARGO_HOME=/cargo_cache
-      - CARGO_TARGET_DIR=/cargo_build_cache
       - SCHEDULER_FLOW=producer
     depends_on:
       hyperswitch-consumer:
@@ -115,37 +141,33 @@ services:
       logs: "promtail"
 
   hyperswitch-consumer:
-    image: rust:latest
-    command: cargo run --bin scheduler -- -f ./config/docker_compose.toml
-    working_dir: /app
+    image: docker.juspay.io/juspaydotin/hyperswitch-consumer:standalone
+    pull_policy: always
+    command: /local/bin/scheduler -f /local/config/docker_compose.toml
     networks:
       - router_net
     profiles:
       - scheduler
     volumes:
-      - ./:/app
-      - cargo_cache:/cargo_cache
-      - scheduler_build_cache:/cargo_build_cache
+      - ./config:/local/config
     environment:
-      - CARGO_HOME=/cargo_cache
-      - CARGO_TARGET_DIR=/cargo_build_cache
       - SCHEDULER_FLOW=consumer
     depends_on:
       hyperswitch-server:
-        condition: service_started
+        condition: service_healthy
     labels:
       logs: "promtail"
     healthcheck:
       test: (ps -e | grep scheduler) || exit 1
-      interval: 120s
-      retries: 4
-      start_period: 30s
+      interval: 10s
+      retries: 3
+      start_period: 5s
       timeout: 10s
 
   hyperswitch-drainer:
-    image: rust:latest
-    command: cargo run --bin drainer -- -f ./config/docker_compose.toml
-    working_dir: /app
+    image: docker.juspay.io/juspaydotin/hyperswitch-drainer:standalone
+    pull_policy: always
+    command: /local/bin/drainer -f /local/config/docker_compose.toml
     deploy:
       replicas: ${DRAINER_INSTANCE_COUNT:-1}
     networks:
@@ -153,18 +175,104 @@ services:
     profiles:
       - full_kv
     volumes:
-      - ./:/app
-      - cargo_cache:/cargo_cache
-      - drainer_build_cache:/cargo_build_cache
-    environment:
-      - CARGO_HOME=/cargo_cache
-      - CARGO_TARGET_DIR=/cargo_build_cache
+      - ./config:/local/config
     restart: unless-stopped
     depends_on:
       hyperswitch-server:
-        condition: service_started
+        condition: service_healthy
     labels:
       logs: "promtail"
+
+  ### Web Client
+  hyperswitch-web:
+    image: docker.juspay.io/juspaydotin/hyperswitch-web:latest
+    pull_policy: always
+    ports:
+      - "9050:9050"
+    networks:
+      - router_net
+    depends_on:
+      hyperswitch-server:
+        condition: service_healthy
+    environment:
+      - ENABLE_LOGGING=true
+      - SDK_ENV=local
+      - ENV_LOGGING_URL=http://localhost:3103
+      - ENV_BACKEND_URL=https://hyperswitch.trendss.net/api
+    labels:
+      - "traefik.enable=true"
+      - "traefik.http.routers.hyperswitch-web.rule=Host(`hyperswitch.trendss.net`) && PathPrefix(`/web`)"
+      - "traefik.http.routers.hyperswitch-web.entrypoints=websecure"
+      - "traefik.http.routers.hyperswitch-web.tls=true"
+      - "traefik.http.services.hyperswitch-web.loadbalancer.server.port=9050"
+      - logs: "promtail"
+
+  ### Control Center
+  hyperswitch-control-center:
+    image: docker.juspay.io/juspaydotin/hyperswitch-control-center:latest
+    pull_policy: always
+    ports:
+      - "9000:9000"
+    environment:
+      - configPath=/tmp/dashboard-config.toml
+      - DASHBOARD_URL=https://hyperswitch.trendss.net/dashboard
+    volumes:
+      - ./config/dashboard.toml:/tmp/dashboard-config.toml
+    depends_on:
+      hyperswitch-server:
+        condition: service_healthy
+      hyperswitch-web:
+        condition: service_started
+    labels:
+      - "traefik.enable=true"
+      - "traefik.http.routers.hyperswitch-control-center.rule=Host(`hyperswitch.trendss.net`) && PathPrefix(`/dashboard`)"
+      - "traefik.http.routers.hyperswitch-control-center.entrypoints=websecure"
+      - "traefik.http.routers.hyperswitch-control-center.tls=true"
+      - "traefik.http.services.hyperswitch-control-center.loadbalancer.server.port=9000"
+      - logs: "promtail"
+
+  create-default-user:
+    image: curlimages/curl-base:latest
+    container_name: create-default-user
+    depends_on:
+      hyperswitch-server:
+        condition: service_healthy 
+      hyperswitch-control-center:
+        condition: service_started
+    environment:
+      - HYPERSWITCH_SERVER_URL=http://hyperswitch-server:8080
+      - HYPERSWITCH_CONTROL_CENTER_URL=http://hyperswitch-control-center:9000  
+    entrypoint:
+      [
+        "/bin/sh",
+        "-c",
+        "apk add --no-cache bash jq && /bin/bash /create_default_user.sh",
+      ]
+    volumes:
+      - ./scripts/create_default_user.sh:/create_default_user.sh
+    networks:
+      - router_net
+  
+  poststart-hook:
+    image: curlimages/curl-base:latest
+    container_name: poststart-hook
+    depends_on:
+      create-default-user:
+        condition: service_completed_successfully
+      hyperswitch-server:
+        condition: service_healthy
+    environment:
+      - ONE_CLICK_SETUP=${ONE_CLICK_SETUP:-false}
+    entrypoint:
+      [
+        "/bin/sh",
+        "-c",
+        "apk add --no-cache bash jq && /bin/bash /poststart_hook.sh",
+      ]
+    volumes:
+      - ./scripts/poststart_hook.sh:/poststart_hook.sh
+    networks:
+      - router_net
 
   ### Clustered Redis setup
   redis-cluster:
@@ -190,37 +298,23 @@ services:
       - redis-cluster
     networks:
       - router_net
-    command: "bash -c 'export COUNT=${REDIS_CLUSTER_COUNT:-3}
-
-      \ if [ $$COUNT -lt 3 ]
-
-      \ then
-
-      \ echo \"Minimum 3 nodes are needed for redis cluster\"
-
-      \ exit 1
-
-      \ fi
-
-      \ HOSTS=\"\"
-
-      \ for ((c=1; c<=$$COUNT;c++))
-
-      \ do
-
-      \ NODE=$COMPOSE_PROJECT_NAME-redis-cluster-$$c:6379
-
-      \ echo $$NODE
-
-      \ HOSTS=\"$$HOSTS $$NODE\"
-
-      \ done
-
-      \ echo Creating a cluster with $$HOSTS
-
-      \ redis-cli --cluster create $$HOSTS --cluster-yes
-
-      \ '"
+    command: |-
+      bash -c 'export COUNT=${REDIS_CLUSTER_COUNT:-3}
+      if [ $$COUNT -lt 3 ]
+      then
+      echo \"Minimum 3 nodes are needed for redis cluster\"
+      exit 1
+      fi
+      HOSTS=\"\"
+      for ((c=1; c<=$$COUNT;c++))
+      do
+      NODE=$COMPOSE_PROJECT_NAME-redis-cluster-$$c:6379
+      echo $$NODE
+      HOSTS=\"$$HOSTS $$NODE\"
+      done
+      echo Creating a cluster with $$HOSTS
+      redis-cli --cluster create $$HOSTS --cluster-yes
+      '
 
   ### Monitoring
   grafana:
@@ -239,18 +333,6 @@ services:
     volumes:
       - ./config/grafana.ini:/etc/grafana/grafana.ini
       - ./config/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yml
-
-  promtail:
-    image: grafana/promtail:latest
-    volumes:
-      - ./logs:/var/log/router
-      - ./config:/etc/promtail
-      - /var/run/docker.sock:/var/run/docker.sock
-    command: -config.file=/etc/promtail/promtail.yaml
-    profiles:
-      - monitoring
-    networks:
-      - router_net
 
   loki:
     image: grafana/loki:latest
@@ -300,8 +382,8 @@ services:
     profiles:
       - monitoring
     ports:
-      - "3200" # tempo
-      - "4317" # otlp grpc
+      - "3200"
+      - "4317"
     restart: unless-stopped
 
   redis-insight:
@@ -309,36 +391,146 @@ services:
     networks:
       - router_net
     profiles:
-      - full_kv
+      - monitoring
     ports:
       - "8001:8001"
     volumes:
       - redisinsight_store:/db
 
-  hyperswitch-control-center:
-    image: docker.juspay.io/juspaydotin/hyperswitch-control-center:latest
-    pull_policy: always
+  kafka0:
+    image: confluentinc/cp-kafka:7.0.5
+    hostname: kafka0
     networks:
       - router_net
     ports:
-      - "9000:9000"
+      - 9092:9092
+      - 9093
+      - 9997
+      - 29092
     environment:
-      - configPath=/tmp/dashboard-config.toml
+      KAFKA_BROKER_ID: 1
+      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
+      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka0:29092,PLAINTEXT_HOST://localhost:9092
+      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
+      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
+      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
+      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
+      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
+      KAFKA_PROCESS_ROLES: "broker,controller"
+      KAFKA_NODE_ID: 1
+      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka0:29093"
+      KAFKA_LISTENERS: "PLAINTEXT://kafka0:29092,CONTROLLER://kafka0:29093,PLAINTEXT_HOST://0.0.0.0:9092"
+      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
+      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
+      JMX_PORT: 9997
+      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka0 -Dcom.sun.management.jmxremote.rmi.port=9997
+    profiles:
+      - olap
     volumes:
-      - ./config/dashboard.toml:/tmp/dashboard-config.toml
+      - ./monitoring/kafka-script.sh:/tmp/update_run.sh
+    command: 'bash -c ''if [ ! -f /tmp/update_run.sh ]; then echo "ERROR: Did you forget the update_run.sh file that came with this docker-compose.yml file?" && exit 1 ; else /tmp/update_run.sh && /etc/confluent/docker/run ; fi'''
 
-  hyperswitch-web-sdk:
-    build:
-      dockerfile_inline: |
-        FROM node:lts
-        RUN git clone https://github.com/juspay/hyperswitch-web.git --depth 1
-        WORKDIR hyperswitch-web
-        RUN npm i --force
-    command: bash -c 'npm run re:build && npx run webpack serve --config webpack.dev.js --host 0.0.0.0'
+  kafka-ui:
+    image: provectuslabs/kafka-ui:latest
     ports:
-      - "9050:9050"
+      - 8090:8080
+    networks:
+      - router_net
+    depends_on:
+      - kafka0
+    profiles:
+      - olap
     environment:
-      sdkEnv: local
-      envSdkUrl: http://localhost:9050
-      envBackendUrl: http://localhost:8080
-      envLoggingUrl: http://localhost:8207
+      KAFKA_CLUSTERS_0_NAME: local
+      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka0:29092
+      KAFKA_CLUSTERS_0_JMXPORT: 9997
+
+  clickhouse-server:
+    image: clickhouse/clickhouse-server:24.3
+    networks:
+      - router_net
+    ports:
+      - "9000"
+      - "8123:8123"
+    volumes:
+      - ./crates/analytics/docs/clickhouse/scripts:/docker-entrypoint-initdb.d
+    environment:
+      - TZ=Asia/Kolkata
+    profiles:
+      - olap
+    ulimits:
+      nofile:
+        soft: 262144
+        hard: 262144
+
+  opensearch:
+    image: opensearchproject/opensearch:2
+    container_name: opensearch
+    hostname: opensearch
+    environment:
+      - "discovery.type=single-node"
+      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=0penS3arc#
+      - LOG_LEVEL=DEBUG
+    profiles:
+      - olap
+    ports:
+      - "9200:9200"
+    networks:
+      - router_net
+
+  opensearch-dashboards:
+    image: opensearchproject/opensearch-dashboards:2
+    ports:
+      - 5601:5601
+    profiles:
+      - olap
+    environment:
+      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
+    networks:
+      - router_net
+
+  vector:
+    image: timberio/vector:latest-debian
+    ports:
+      - "8686"
+      - "9598"
+      - "3103:3103"
+    profiles:
+      - olap
+    environment:
+      KAFKA_HOST: "kafka0:29092"
+    networks:
+      - router_net
+    volumes:
+      - ./config/vector.yaml:/etc/vector/vector.yaml
+      - /var/run/docker.sock:/var/run/docker.sock
+
+  hyperswitch-demo:
+    image: docker.juspay.io/juspaydotin/hyperswitch-react-demo-app:latest
+    pull_policy: always
+    ports:
+      - "9060:9060"
+      - "5252:5252"
+    networks:
+      - router_net
+    profiles:
+      - full_setup
+    depends_on:
+      hyperswitch-server:
+        condition: service_healthy
+      hyperswitch-web:
+        condition: service_started
+    environment:
+      - HYPERSWITCH_PUBLISHABLE_KEY=your_publishable_key # Replace with your Hyperswitch publishable key
+      - HYPERSWITCH_SECRET_KEY=your_api_key # Replace with your Hyperswitch API key
+      - PROFILE_ID=your_profile_id # Replace with your Hyperswitch profile ID
+      - HYPERSWITCH_CLIENT_URL=https://hyperswitch.trendss.net/web
+      - HYPERSWITCH_SERVER_URL=https://hyperswitch.trendss.net/api
+    labels:
+      - "traefik.enable=true"
+      - "traefik.http.routers.hyperswitch-demo.rule=Host(`hyperswitch.trendss.net`) && PathPrefix(`/demo`)"
+      - "traefik.http.routers.hyperswitch-demo.entrypoints=websecure"
+      - "traefik.http.routers.hyperswitch-demo.tls=true"
+      - "traefik.http.services.hyperswitch-demo.loadbalancer.server.port=9060"
+      - logs: "promtail"
+```
